import type { FamilyMember } from '../types/FamilyMember';

export const familyData: FamilyMember[] = [
  { id: "1", name: 'Janab Bhinak Miyan Marhoom', fatherId: null, isDeceased: true },
  { id: "2", name: 'Janab Jagroop Ansari Marhoom', fatherId: "1", isDeceased: true },
  { id: "3", name: 'Janab Amrit Ansari Marhoom', fatherId: "2", isDeceased: true },
  { id: "4", name: 'Janab Sohar Ansari Marhoom', fatherId: "2", isDeceased: true },
  { id: "5", name: 'Janab Mohar Ansari Marhoom', fatherId: "2", isDeceased: true },
  { id: "6", name: 'Janab Phoolchand Ansari Marhoom', fatherId: "2", isDeceased: true },
  { id: "7", name: 'Janab Ramzan Ansari Marhoom', fatherId: "3", isDeceased: true },
  { id: "8", name: 'Janab Ghulaman Ansari Marhoom', fatherId: "4", isDeceased: true },
  { id: "9", name: 'Janab Shahzad Ansari Marhoom', fatherId: "5", isDeceased: true },
  { id: "10", name: 'Janab Islam Ansari Marhoom', fatherId: "7", isDeceased: true },
  { id: "11", name: 'Janab Ismail Ansari Marhoom', fatherId: "7", isDeceased: true },
  { id: "12", name: 'Janab Jaan Mohammad Ansari Marhoom', fatherId: "8", isDeceased: true },
  { id: "13", name: 'Janab Wajuddin Ansari Marhoom', fatherId: "8", isDeceased: true },
  { id: "14", name: 'Janab Roj Mohammad Ansari Marhoom', fatherId: "8", isDeceased: true },
  { id: "15", name: 'Janab Nehal Ansari Marhoom', fatherId: "9", isDeceased: true },
  { id: "16", name: 'Janab Khursheed Ansari Marhoom', fatherId: "10", isDeceased: true },
  { id: "17", name: 'Janab Sukhruddin Ansari Marhoom', fatherId: "34", isDeceased: true },
  { id: "18", name: 'Janab Nisar Ansari Marhoom', fatherId: "39", isDeceased: true },
  { id: "19", name: 'Janab Asfaque Ansari Marhoom', fatherId: "40", isDeceased: true },
  { id: "20", name: 'Janab Rahimuddin Ansari Marhoom', fatherId: "30", isDeceased: true },
  { id: "21", name: 'Janab Ahmed Ansari Marhoom', fatherId: "27", isDeceased: true },
  { id: "22", name: 'Janab Ghulam Rasool Ansari Marhoom', fatherId: "27", isDeceased: true },
  { id: "23", name: 'Janab Manroop Ansari Marhoom', fatherId: "1", isDeceased: true },
  { id: "24", name: 'Janab Bechan Ansari Marhoom', fatherId: "23", isDeceased: true },
  { id: "25", name: 'Janab Ibrahim Ansari Marhoom', fatherId: "23", isDeceased: true },
  { id: "26", name: 'Janab Ali Mohammad Ansari Marhoom', fatherId: "23", isDeceased: true },
  { id: "27", name: 'Janab Yaseen Ansari Marhoom', fatherId: "24", isDeceased: true },
  { id: "28", name: 'Janab Sobhan Ansari Marhoom', fatherId: "25", isDeceased: true },
  { id: "29", name: 'Janab Sofi Ansari Marhoom', fatherId: "25", isDeceased: true },
  { id: "30", name: 'Janab Mehangu Ansari Marhoom', fatherId: "26", isDeceased: true },
  { id: "31", name: 'Janab Jafar Ansari Marhoom', fatherId: "26", isDeceased: true },
  { id: "32", name: 'Janab Rojan Ansari Marhoom', fatherId: "26", isDeceased: true },
  { id: "33", name: 'Janab Dargahi Ansari Marhoom', fatherId: "26", isDeceased: true },
  { id: "34", name: 'Janab Ghulam Mohammad Ansari Marhoom', fatherId: "27", isDeceased: true },
  { id: "35", name: 'Janab Reyasat Ansari Marhoom', fatherId: "28", isDeceased: true },
  { id: "36", name: 'Janab Saleem Ansari Marhoom', fatherId: "28", isDeceased: true },
  { id: "37", name: 'Janab Yunus Ansari Marhoom', fatherId: "28", isDeceased: true },
  { id: "38", name: 'Janab Shahid Ansari Marhoom', fatherId: "29", isDeceased: true },
  { id: "39", name: 'Janab Rafiq Ansari Marhoom', fatherId: "29", isDeceased: true },
  { id: "40", name: 'Janab Rasid Ansari Marhoom', fatherId: "29", isDeceased: true },
  { id: "41", name: 'Janab Rahim Ansari Marhoom', fatherId: "29", isDeceased: true },
  { id: "42", name: 'Janab Naimuddin Ansari Marhoom', fatherId: "30", isDeceased: true },
  { id: "43", name: 'Janab Asgar Ansari Marhoom', fatherId: "31", isDeceased: true },
  { id: "44", name: 'Janab Vilayat Ansari Marhoom', fatherId: "32", isDeceased: true },
  { id: "45", name: 'Janab Ali Hussain Ansari Marhoom', fatherId: "32", isDeceased: true },
  { id: "46", name: 'Janab Badaruddin Ansari Marhoom', fatherId: "33", isDeceased: true },
  { id: "47", name: 'Janab Anwarul Haq Ansari Marhoom', fatherId: "22", isDeceased: true },
  { id: "48", name: 'Janab Anees Ansari Marhoom', fatherId: "47", isDeceased: true },
  { id: "49", name: 'Janab Shivcharan Ansari Marhoom', fatherId: "1", isDeceased: true },
  { id: "50", name: 'Janab Lokan Ansari Marhoom', fatherId: "49", isDeceased: true },
  { id: "51", name: 'Janab Sadalli Ansari Marhoom', fatherId: "49", isDeceased: true },
  { id: "52", name: 'Janab Imaman Ansari Marhoom', fatherId: "50", isDeceased: true },
  { id: "53", name: 'Janab Madina Ansari Marhoom', fatherId: "50", isDeceased: true },
  { id: "54", name: 'Janab Kabir Ansari Marhoom', fatherId: "51", isDeceased: true },
  { id: "55", name: 'Janab Kareem Ansari Marhoom', fatherId: "51", isDeceased: true },
  { id: "56", name: 'Janab Qurban Ansari Marhoom', fatherId: "55", isDeceased: true },
  { id: "57", name: 'Janab Islamuddin Ansari Marhoom', fatherId: "52", isDeceased: true },
  { id: "58", name: 'Janab Jaleel Ansari Marhoom', fatherId: "53", isDeceased: true },
  { id: "59", name: 'Janab Sulaiman Ansari Marhoom', fatherId: "53", isDeceased: true },
  { id: "60", name: 'Janab Mohammad Ali Ansari Marhoom', fatherId: "53", isDeceased: true },
  { id: "61", name: 'Janab Muslim Ansari Marhoom', fatherId: "57", isDeceased: true },
  { id: "62", name: 'Janab Abdur Rahim Ansari Marhoom', fatherId: "60", isDeceased: true },
  { id: "63", name: 'Janab Mainuddin Ansari Marhoom', fatherId: "58", isDeceased: true },
  { id: "64", name: 'Janab Jahangir Ansari Marhoom', fatherId: "12", isDeceased: true },
  { id: "65", name: 'Janab Akbar Ansari', fatherId: "31", isDeceased: false },
  { id: "66", name: 'Asmuddin Ansari', fatherId: "65", isDeceased: false },
  { id: "67", name: 'Najmuddin Noori', fatherId: "65", isDeceased: false },
  { id: "68", name: 'Mosim Ansari', fatherId: "65", isDeceased: false },
  { id: "69", name: 'Jashmuddin Ansari', fatherId: "65", isDeceased: false },
  { id: "70", name: 'Wasim Ansari', fatherId: "65", isDeceased: false },
  { id: "71", name: 'Ashif Raza', fatherId: "66", isDeceased: false },
  { id: "72", name: 'Shahid Raza', fatherId: "66", isDeceased: false },
  { id: "73", name: 'Masum Raza', fatherId: "67", isDeceased: false },
  { id: "74", name: 'Wasris Raza', fatherId: "66", isDeceased: false },
  { id: "75", name: 'Taushif Raza', fatherId: "68", isDeceased: false },
  { id: "76", name: 'Faizan Raza', fatherId: "66", isDeceased: false },
  { id: "77", name: 'Taiyab Raza', fatherId: "69", isDeceased: false },
  { id: "78", name: 'Taukeer Raza', fatherId: "68", isDeceased: false },
  { id: "79", name: 'Tauhid Raza', fatherId: "68", isDeceased: false },
  { id: "80", name: 'Tamzid Raza', fatherId: "69", isDeceased: false },
  { id: "81", name: 'Asad Raza', fatherId: "70", isDeceased: false },
  { id: "82", name: 'Janab Jamaluddin Ansari Marhoom', fatherId: "46", isDeceased: true }
];

